// Reference date: 2026-05-30 (today when this was written)
// Dates are set relative to that so urgency labels look realistic in a demo build.

export const MOCK_DATA = {
  lastScanned: "2026-05-30T07:00:00Z",
  events: [
    {
      id: "demo_001",
      title: "Picture Day — Wear School Colors",
      date: "2026-05-30",
      category: "school",
      priority: "high",
      source: "Springfield Elementary",
      notes: "All grades. Order photos online by June 7.",
      link: "https://example.com/school-photos",
      source_message_id: "18f2b3c4d5e6f001",
      source_thread_id: "18f2b3c4d5e6f001",
      source_subject: "Picture Day Reminder — May 30",
      dismissed: false,
      deleted: false,
      manually_added: false,
    },
    {
      id: "demo_002",
      title: "U8 Soccer Tournament",
      date: "2026-05-31",
      category: "soccer",
      priority: "high",
      source: "Riverside Soccer Club",
      notes: "Arrive by 8:30am. Bring extra water and sunscreen. Green jersey.",
      link: null,
      source_message_id: "18f2b3c4d5e6f002",
      source_thread_id: "18f2b3c4d5e6f002",
      source_subject: "This Weekend — U8 Tournament Schedule",
      dismissed: false,
      deleted: false,
      manually_added: false,
    },
    {
      id: "demo_003",
      title: "Scouts Camping Trip — Permission Slip Due",
      date: "2026-06-01",
      category: "scouts",
      priority: "medium",
      source: "Pack 142",
      notes: "Trip is June 13–15 at Clearwater Lake. Return slip with $35 deposit.",
      link: "https://example.com/scouts-permission",
      source_message_id: "18f2b3c4d5e6f003",
      source_thread_id: "18f2b3c4d5e6f003",
      source_subject: "Pack 142 — Camping Trip Permission Slip",
      dismissed: false,
      deleted: false,
      manually_added: false,
    },
    {
      id: "demo_004",
      title: "Daycare Field Trip Waiver — Science Museum",
      date: "2026-06-04",
      category: "daycare",
      priority: "medium",
      source: "Little Stars Daycare",
      notes: "Submit the online waiver before June 4. Kids leave at 9am.",
      link: "https://example.com/field-trip-waiver",
      source_message_id: "18f2b3c4d5e6f004",
      source_thread_id: "18f2b3c4d5e6f004",
      source_subject: "Field Trip Information — Science Museum June 4",
      dismissed: false,
      deleted: false,
      manually_added: false,
    },
    {
      id: "demo_005",
      title: "GFT Belt Testing",
      date: "2026-06-13",
      category: "GFT",
      priority: "medium",
      source: "GFT After School",
      notes: "Students testing for next belt level. Full uniform required. Testing starts at 5:30pm.",
      link: null,
      source_message_id: "18f2b3c4d5e6f005",
      source_thread_id: "18f2b3c4d5e6f005",
      source_subject: "June Belt Testing — GFT After School",
      dismissed: false,
      deleted: false,
      manually_added: false,
    },
    {
      id: "demo_006",
      title: "Summer Camp Early-Bird Registration Deadline",
      date: "2026-06-20",
      category: "school",
      priority: "high",
      source: "Springfield Elementary",
      notes: "Camp runs July 14–18. Register by June 20 to lock in the early-bird rate ($50 off).",
      link: "https://example.com/summer-camp-2026",
      source_message_id: "18f2b3c4d5e6f006",
      source_thread_id: "18f2b3c4d5e6f006",
      source_subject: "Summer Camp 2026 — Registration Open",
      dismissed: false,
      deleted: false,
      manually_added: false,
    },
    {
      id: "demo_007",
      title: "End of Year Celebration",
      date: "2026-06-27",
      category: "school",
      priority: "low",
      source: "Springfield Elementary",
      notes: "Families welcome 2–4pm. Light refreshments provided. Parking in the rear lot.",
      link: null,
      source_message_id: "18f2b3c4d5e6f007",
      source_thread_id: "18f2b3c4d5e6f007",
      source_subject: "End of Year Celebration — All Families Welcome",
      dismissed: false,
      deleted: false,
      manually_added: false,
    },
    {
      id: "demo_008",
      title: "School Supply Drive",
      date: null,
      category: "other",
      priority: "medium",
      source: "Springfield PTA",
      notes: "Drop off unused supplies in the front office any time before the last day of school.",
      link: null,
      dismissed: false,
      deleted: false,
      manually_added: true,
    },
    {
      id: "demo_009",
      title: "Soccer Season Wrap-Up Party",
      date: "2026-05-22",
      category: "soccer",
      priority: "low",
      source: "Riverside Soccer Club",
      notes: "Pizza and trophies for all players. Great season!",
      link: null,
      source_message_id: "18f2b3c4d5e6f009",
      source_thread_id: "18f2b3c4d5e6f009",
      source_subject: "Wrap-Up Party This Thursday — U8",
      dismissed: true,
      deleted: false,
      manually_added: false,
    },
  ],
  digestGroups: [
    {
      source: "School",
      category: "school",
      week_of: "2026-05-25",
      bullets: [
        { text: "Ms. Henderson's class took part in the second session of a Watershed Workshop, walking to a nearby construction site to see a real water main up close — a hands-on way to connect classroom learning to the infrastructure in your neighbourhood. Enough parent volunteers signed up to make it happen.", link: null },
        { text: "Several important June events to plan around: an early dismissal day, a Pro-D Day when school is closed entirely, and Sports Day with another early dismissal — worth arranging childcare or an outing in advance.", link: null },
        { text: "The end of the year is approaching fast. Upcoming ceremonies include a Grade 7 Leaving Ceremony, an Indigenous Peoples Day Assembly, and a Farewell Assembly. The last day of school will be only one hour long.", link: null },
        { text: "The school district sent a survey asking families to share feedback on Spring Break Camp 2026 to help shape next year's program. If your family used it, your input is welcome.", link: "https://example.com/spring-camp-survey" },
      ],
    },
    {
      source: "Daycare",
      category: "daycare",
      week_of: "2026-05-25",
      bullets: [
        { text: "Maya sent the May newsletter from Little Stars Daycare. The kids have been exploring nature as scientists — visiting Riverside Park, making giant paper-plate flowers, experimenting with magnets, and painting ideas inspired by 'The Very Hungry Caterpillar.' They also planted seeds in their Mother's Day pots — keep an eye out for sprouts at home!", link: null },
        { text: "The children are now working on a Father's Day surprise, so expect some secretive crafting energy if your child mentions it.", link: null },
        { text: "Maya will be stepping off the floor soon as a new baby is on the way. Mr. Torres and Ms. Chen are taking over daily communications — please give at least a day's notice for schedule changes, especially late arrivals, as the kids may head to the park spontaneously in the mornings.", link: null },
        { text: "A farewell party is being planned for classmate Sophie, whose family is relocating. Monthly fees are also due at the start of June to avoid late charges.", link: null },
      ],
    },
    {
      source: "Scouts",
      category: "scouts",
      week_of: "2026-05-25",
      bullets: [
        { text: "Emma's Beaver colony joined an all-colonies hike at Riverside Park this week, working on trail skills and exploring local nature. Kids were asked to bring water, a snack, a headlamp, and grippy shoes — a great sign the outdoor program is ramping up as the year winds down.", link: null },
        { text: "The big news: Year End Camp at Camp Ridgewood is a full Friday-to-Sunday overnight — the whole family is welcome and siblings can come as guests. The focus is camping and trail skills badges. No bus, so carpooling needs to be arranged. RSVPs are needed so organizers can plan.", link: "https://example.com/scouts-camp-rsvp" },
      ],
    },
    {
      source: "Soccer",
      category: "soccer",
      week_of: "2026-05-25",
      bullets: [
        { text: "Luca's team had practice at a local school field this week, with an early arrival time before the session began. The spring season is actively underway with regular training continuing.", link: null },
      ],
    },
    {
      source: "GFT After School",
      category: "GFT",
      week_of: "2026-05-25",
      bullets: [
        { text: "Big news for Emma: the academy has officially confirmed her for an upcoming belt test, recognizing she has earned all the required stripes. The instructor noted she'll be assessed during her next few regular classes before the big day. The belt test fee must be paid in cash beforehand — check the original invitation for the deadline.", link: null },
        { text: "Emma is also enrolled in a Pro-D Day Parkour & Tumbling camp at Peak Athletics, running as a full 6.5-hour day — a great way to keep her active and engaged on the school closure day.", link: null },
        { text: "The academy hosted a free Kids Confidence Workshop last Saturday — an intro BJJ class for kids aged 6–12, open to non-members, with pizza included. A low-key way to experience the program.", link: null },
      ],
    },
  ],
}